---
- name: Install Java, Jenkins, kubectl, Docker, gcloud, and configure Jenkins user
  hosts: localhost
  become: yes
  connection: local

  tasks:

  - name: Ensure keyring directories exist
    file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
    loop:
      - /etc/apt/keyrings
      - /usr/share/keyrings

  - name: Download Jenkins GPG key
    get_url:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      dest: /etc/apt/keyrings/jenkins-keyring.asc
      mode: '0644'

  - name: Add Jenkins APT repository
    copy:
      dest: /etc/apt/sources.list.d/jenkins.list
      content: |
        deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
      mode: '0644'

  - name: Install base packages including dependencies for gcloud
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - gnupg
        - curl
      state: present
      update_cache: yes

  - name: Import Google Cloud public key
    shell: |
      curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
    args:
      creates: /usr/share/keyrings/cloud.google.gpg

  - name: Add Google Cloud SDK repository
    copy:
      dest: /etc/apt/sources.list.d/google-cloud-sdk.list
      content: |
        deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main
      mode: '0644'

  - name: Update APT cache
    apt:
      update_cache: yes

  - name: Install required packages
    apt:
      name:
        - openjdk-17-jdk
        - curl
        - jenkins
        - google-cloud-cli
        - google-cloud-sdk-gke-gcloud-auth-plugin
      state: present

  - name: Verify GKE gcloud auth plugin version
    command: gke-gcloud-auth-plugin --version
    register: gke_auth_version
    ignore_errors: yes

  - name: Display GKE Auth Plugin Version
    debug:
      msg: "{{ gke_auth_version.stdout | default('Plugin not found or failed to execute') }}"

  - name: Download latest stable kubectl
    shell: |
      curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    args:
      chdir: /tmp
      creates: /tmp/kubectl

  - name: Install kubectl to /usr/local/bin
    copy:
      src: /tmp/kubectl
      dest: /usr/local/bin/kubectl
      mode: '0755'
      owner: root
      group: root

  - name: Download Docker install script
    get_url:
      url: https://get.docker.com
      dest: /tmp/install-docker.sh
      mode: '0755'

  - name: Run Docker install script
    command: sh /tmp/install-docker.sh
    args:
      creates: /usr/bin/docker

  - name: Add jenkins user to docker group
    user:
      name: jenkins
      groups: docker
      append: yes

  - name: Notify about group membership change
    debug:
      msg: "Jenkins may need a service restart or re-login to apply Docker group changes."
